kind: pipeline
type: docker
name: test
steps:
  - name: build-serial
    image: wandersonca/gcc
    commands:
    - make serial
  - name: test-serial
    image: wandersonca/gcc
    commands:
    - ./bin/serial-cracker -bl -c 4 -p $(echo -n 'test' | sha256sum) --verbose
    - ./bin/serial-cracker -d dictionary_files/100_pass.txt -p $(echo -n '123456' | sha256sum)
  - name: build-mpi
    image: wandersonca/mpi
    commands:
    - make mpi
  - name: test-mpi
    image: wandersonca/mpi
    commands:
    - mpirun --allow-run-as-root -np 1 ./bin/mpi-cracker -bluns -p $(echo -n 'test' | sha256sum) -v
    - mkdir -p temp
    - split -d -l 25 dictionary_files/100_pass.txt temp/file_
    - mpirun --allow-run-as-root -np 1 ./bin/mpi-cracker -d temp -p $(echo -n '123456' | sha256sum) -v
  - name: build-omp
    image: wandersonca/gcc
    commands:
    - make omp
  - name: test-omp
    image: wandersonca/gcc
    commands:
    - OMP_NUM_THREADS=4 ./bin/omp-cracker -d dictionary_files/100_pass.txt -p $(echo -n '123456' | sha256sum) -v
    - OMP_NUM_THREADS=4 ./bin/omp-cracker -bluns -p $(echo -n 'test' | sha256sum) -v
